### ISSUE TITLE
oppo watch 2使用中的各种问题

### ISSUE THREAD

**Issue by 24kcsplus** [JackuXL/WearMusic#6]
1.我喜欢的音乐一直显示加载失败
2.私人FM提醒未登录，但已登录
3.进入更新界面闪退，之后进入便都会闪退，只能卸载重装
4.进入反馈界面闪退，但之后还可进入
以上问题能够稳定复现

另外，希望能够打破手表版权限制（虽然不太可能吧）

祝作者事业顺利，身体健康

**Comment by 24kcsplus** [comment]
进入是指进入软件而非功能界面

**Comment by 24kcsplus** [comment]
加一条，音乐云盘会提示无音乐，但实际有音乐存在音乐云盘中

**Comment by 24kcsplus** [comment]
版本3.1

**Comment by JackuXL** [comment]
最近也整了台OW2，确实有这个问题，已经修复了，请等待v3.5

**Comment by 24kcsplus** [comment]
请问作者，v3.5什么时候做好（~~催更~~

**Comment by JackuXL** [comment]
等寒假吧，最近都忙着考试没啥流量
